coverage_service: coveralls
xcodeproj: NotchUtility.xcodeproj
scheme: NotchUtility
arch: arm64
source_directory: NotchUtility
output_directory: coverage
ignore:
  - NotchUtilityTests/*
  - NotchUtilityUITests/*

