# SwiftLint Configuration for NotchUtility

# Paths to include during linting
included:
  - NotchUtility/
  - NotchUtilityTests/
  - NotchUtilityUITests/

# Paths to exclude during linting
excluded:
  - Carthage/
  - Pods/
  - .build/
  - DerivedData/
  - NotchUtility.xcodeproj/
  - NotchUtility/Assets.xcassets/
  - NotchUtility/ViewModels/NotchViewModel+Events.swift

# Rules to run
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - empty_count
  - empty_string
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - force_unwrapping
  - implicit_return
  - joined_default_parameter
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - nimble_operator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - strict_fileprivate
  - switch_case_alignment
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

# Rules to disable
disabled_rules:
  - todo
  - line_length # We'll set a custom length below
  - trailing_whitespace
  - vertical_whitespace
  - trailing_newline

# Rule configurations
line_length:
  warning: 120
  error: 150

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 400
  error: 500

function_body_length:
  warning: 40
  error: 60

cyclomatic_complexity:
  warning: 10
  error: 15

nesting:
  type_level:
    warning: 2
  statement_level:
    warning: 5

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - x
    - y

force_unwrapping:
  severity: warning

# Reporter type
reporter: "xcode" 